import { Inter } from "next/font/google";
import "./globals.css";
import MianHeader from "@/components/mian-header";
import MenuState from "@/components/menu-state";
import Container from "@/Ui/container";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Treveller",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#222] text-white `}>
        <Container>
          <MenuState/>
        </Container>
        {children}
        
        </body>
    </html>
  );
}
